<?php echo showErrors($this->user->getErrors()); ?>

<div class="panel panel-default">
    <div class="panel-heading"><?php echo $this->title; ?></div>
    <div class="panel-body">
        <?php $form = formFor($this->user); ?>
        <?php echo $form->start($this->url, $this->method, array('class' => 'form-horizontal')); ?>

        <div class="form-group">
            <?php echo $form->label('login', array('class' => 'control-label col-lg-2')); ?>

            <div class="col-lg-10">
                <?php echo $form->textField('login') ?>
            </div>
        </div>

        <div class="form-group">
            <?php echo $form->label('password', array('class' => 'control-label col-lg-2')); ?>

            <div class="col-lg-10">
                <?php echo $form->passwordField('password'); ?>
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-offset-2 col-lg-10">
                <button type="submit" class="btn btn-primary">Save</button>
                <?php echo linkButton(array('name' => 'cancel', 'value' => 'Cancel', 'url' => usersPath(), 'class' => "btn btn-default")); ?>
            </div>
        </div>

        <?php echo $form->end(); ?>
    </div>
</div>


