
<?= showNotices() ?>

<div class="panel panel-default">
    <div class="panel-heading">Users</div>
    <div class="panel-body">
        <?= linkButton(array('name' => 'add_new', 'value' => 'Add', 'url' => freshUserPath(), 'class' => "btn btn-primary")) ?>
        <table class="table table-hover">
            <thead>
            <tr>
                <th>#</th>
                <th>Login</th>
            </tr>
            </thead>
            <tbody>
            <? foreach ($this->users as $index => $user): ?>
                <tr>
                    <td><?= linkTo($index, userPath($user->id))  ?></td>
                    <td><?= linkTo($user->login, userPath($user->id))  ?></td>
                </tr>
            <? endforeach ?>
            </tbody>
        </table>
    </div>
</div>

