<?php echo showNotices(); ?>

<div class="panel panel-default">
    <div class="panel-heading">Users</div>
    <div class="panel-body">
        <?php echo linkButton(['name' => 'add_new', 'value' => 'Add', 'url' => freshUserPath(), 'class' => "btn btn-primary"]); ?>
        <table class="table table-hover">
            <thead>
            <tr>
                <th>#</th>
                <th>Login</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->users as $index => $user): ?>
                <tr>
                    <td><?php echo linkTo($index, userPath($user->id)); ?></td>
                    <td><?php echo linkTo($user->login, userPath($user->id)); ?></td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>

