<?php echo showNotices(); ?>

<div class="panel panel-default">
    <div class="panel-heading">User</div>
    <div class="panel-body">
        <div>
            <?php echo labelTag('login', 'login', ['class' => 'control-label col-lg-2']); ?>
            <div class="col-lg-10">
                <?php echo $this->user->login; ?>
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-offset-2 col-lg-10">
                <?php echo linkButton(['name' => 'edit', 'value' => 'Edit', 'url' => editUserPath($this->user->id), 'class' => "btn btn-primary"]); ?>
                <?php echo linkButton(['name' => 'cancel', 'value' => 'Cancel', 'url' => usersPath(), 'class' => "btn btn-default"]); ?>
            </div>
        </div>
    </div>
</div>