language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3

env:
    - db=postgres

before_script:
    - echo 'date.timezone = "Europe/Warsaw"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - composer install
    - psql -c 'create database ouzo_test' -U postgres
    - environment=test ./db.sh db:migrate

script:
    - phpunit --configuration phpunit.xml test
