<meta charset="utf-8"/>
<style>
    .content {
        margin: 7em auto 0 auto;
        height:50%;
        text-align: center;
        background-color: #f4f4f4;
    }
    .title {
        top: 20%;
        font-size: 100px;
        margin-bottom: 30px;
    }
    .trace {
        text-align: left;
        display: inline-block
    }
</style>

<div class="content">
    <div class="title">Oops, 404!</div>
    <div><strong>The page you were looking for could not be found. Error ID: <?php echo \Ouzo\FrontController::$requestId; ?></strong></div>

    <?php if (\Ouzo\Config::getValue('debug')): ?>
        <div>
            <p>Message: <strong><?php echo $errorMessage; ?></strong></p>
            <div class="trace">
                Trace:
                <pre><?php echo trim($errorTrace); ?></pre>
            </div>
        </div>
    <?php endif; ?>
</div>
