<meta charset="utf-8"/>
<style>
    body {
        margin: 0;
        padding: 10px;
    }

    #errorTrace {
        margin: 0;
        font-size: 16px;
        border: 2px solid;
        background-color: #FF9999;
        padding: 10px;
    }

    #message {
        margin: 0;
    }

    #trace {
        margin-top: 10px;
    }

    pre {
        font-size: 12px;
        overflow: auto;
        width: 95%
    }
</style>
<div id="errorTrace">
    <p id="message">Message: <strong><?php echo $errorMessage; ?></strong></p>
    <hr/>
    <div id="trace"> Error ID: <?php echo \Ouzo\FrontController::$requestId; ?> </div>
    <hr/>
</div>
